version: 2

models:
  - name: dim_patients
    description: >
      Dimension table containing unique patient-level demographic information.
      Each patient appears once, identified by patient_id (surrogate key). Stores
      cleaned attributes such as gender, race, and age group.
    columns:
      - name: patient_id
        description: Surrogate key assigned to each patient. Serves as the primary key for this dimension.
        tests:
          - not_null
          - unique

      - name: patient_nbr
        description: Original patient identifier from the raw dataset. Deduplicated to 1 row per patient.
        tests:
          - not_null
          - unique

      - name: gender
        description: Patient gender (Male, Female, Unknown).
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Male', 'Female', 'Unknown']

      - name: race
        description: Patient race (Caucasian, AfricanAmerican, Asian, Hispanic, Other, Unknown).
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Caucasian','AfricanAmerican','Asian','Hispanic','Other','Unknown']

      - name: age_group
        description: Patient age grouped into ranges (e.g., 20-30, 30-40, ..., 90-100).
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['0-10','10-20','20-30','30-40','40-50','50-60','60-70','70-80','80-90','90-100']

  - name: dim_diagnosis
    description: >
      Dimension table containing 10 broad diagnosis categories derived from ICD-9 codes.
      Simplifies analysis by grouping thousands of codes into categories.
    columns:
      - name: diagnosis_id
        tests:
          - not_null
          - unique
      - name: diagnosis_category
        tests:
          - not_null

  - name: dim_admission
    description: >
      Dimension table mapping admission_type_id codes to descriptive labels.
    columns:
      - name: admission_type_id
        tests:
          - not_null
          - unique
      - name: admission_type
        tests:
          - not_null

  - name: dim_discharge
    description: >
      Dimension table mapping discharge_disposition_id codes (1–29) to descriptive labels.
    columns:
      - name: discharge_disposition_id
        tests:
          - not_null
          - unique
      - name: discharge_disposition
        tests:
          - not_null

  - name: dim_admission_source
    description: >
      Dimension table mapping admission_source_id codes (1–21) to descriptive labels.
    columns:
      - name: admission_source_id
        tests:
          - not_null
          - unique
      - name: admission_source
        tests:
          - not_null

  - name: dim_medical_specialty
    description: >
      Dimension table containing grouped medical specialties. Rare categories combined into 'Other'.
    columns:
      - name: specialty_id
        tests:
          - not_null
          - unique
      - name: medical_specialty
        tests:
          - not_null

  - name: dim_payer
    description: >
      Dimension table mapping payer codes to insurance names. Groups rare codes into 'Other' or 'Unknown'.
    columns:
      - name: payer_id
        tests:
          - not_null
          - unique
      - name: payer_code
        tests:
          - not_null
      - name: payer_name
        tests:
          - not_null

  - name: fact_visits
    description: >
      Central fact table at the encounter level. Each row represents one hospital visit,
      linked to patients, admission type, admission source, discharge disposition,
      diagnoses, payer, and medical specialty.
    columns:
      - name: encounter_id
        tests:
          - not_null
          - unique
      - name: patient_id
        tests:
          - not_null

  - name: fact_medications
    description: >
      Bridge fact table that unpivots medication columns into rows for analysis.
    columns:
      - name: encounter_id
        tests:
          - not_null
      - name: medication
        tests:
          - not_null
      - name: status
        tests:
          - not_null
